name: pppc_companion
description: "Компаньйон студента Полтавського політехнічного коледжу."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.3
  http: ^0.13.3
  xml: ^5.3.1
  url_launcher: ^6.3.1
  card_loading: ^0.3.0
  weather: ^3.0.0
  parallax_rain: ^1.1.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  line_icons: ^2.0.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  dynamic_color: ^1.7.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_html: ^3.0.0-beta.2
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/svg/ППФК.svg
    - assets/img/news.jpg
    - assets/img/oleh.png
    - assets/img/noavatar.png
    - assets/gif/spongebob-i-quit.gif
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  adaptive_icon_background: "assets/launcher_icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/launcher_icon/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/launcher_icon/ic_launcher_monochrome.png"