name: pppc_companion
description: "Компаньйон студента Полтавського політехнічного коледжу."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.3
  http: ^0.13.3
  xml: ^5.3.1
  url_launcher: ^6.3.1
  card_loading: ^0.3.0
  weather: ^3.0.0
  parallax_rain: ^1.1.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/svg/ППФК.svg
    - assets/img/news.jpg
    - assets/img/oleh.png
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300