name: pppc_companion
description: "Компаньйон студента Полтавського політехнічного коледжу."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  http: ^0.13.3
  xml: ^6.5.0
  url_launcher: ^6.3.1
  card_loading: ^0.3.0
  weather: ^3.0.0
  parallax_rain: ^1.1.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  line_icons: ^2.0.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  dynamic_color: ^1.7.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_html: ^3.0.0-beta.2
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  firebase_storage: ^12.4.2
  google_maps_flutter: ^2.10.1
  vibration: ^3.1.3
  sleek_circular_slider: ^2.0.1
  flutter_simple_calculator: ^2.3.0
  translator: ^0.1.7
  wifi_iot: ^0.3.19+2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/svg/ППФК.svg
    - assets/svg/transport/bus.svg
    - assets/svg/transport/route.svg
    - assets/svg/transport/trolleybus.svg
    - assets/svg/transport/intercity.svg
    - assets/svg/transport/regional.svg
    - assets/svg/transport/train.svg
    - assets/img/news.jpg
    - assets/img/oleh.png
    - assets/img/liubquantilogo.png
    - assets/img/pppclogo.png
    - assets/img/noavatar.png
    - assets/gif/spongebob-i-quit.gif
    - assets/img/map/1.jpg
    - assets/img/map/2.jpg
    - assets/img/map/3.jpg

    - assets/json/stations.json

    - assets/svg/PoltavaRegion.svg
    - assets/svg/PoltavaRegionCities.svg
    - assets/svg/PoltavaRegionBorder.svg
    - assets/svg/PoltavaRegionBordersOther.svg
    - assets/svg/PoltavaRegionLogo.svg

    - assets/json/map/auberginemap.json
    - assets/json/map/darkmap.json
    - assets/json/map/nightmap.json
    - assets/json/map/retromap.json
    - assets/json/map/silvermap.json

    - assets/img/map-styles/default.png
    - assets/img/map-styles/aubergine.png
    - assets/img/map-styles/dark.png
    - assets/img/map-styles/night.png
    - assets/img/map-styles/retro.png
    - assets/img/map-styles/silver.png
  
  
    - assets/badges/square-terminal.svg
    - assets/badges/test-tube.svg

  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  adaptive_icon_background: "assets/launcher_icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/launcher_icon/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/launcher_icon/ic_launcher_monochrome.png"