name: pppc_companion_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.6 # Додаємо пакет Fluent UI
  intl: ^0.19.0 # Для форматування часу

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
